/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import classe.link_bd;
import static classe.link_bd.statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Aluno
 */
public class telarec extends javax.swing.JFrame {
    
    int seq;
    public String tipo = "";
    
    link_bd objbd = new link_bd();
    
    String pegaHora, pegaData;
    
    public telarec() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbsenha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbhoraticket = new javax.swing.JLabel();
        lbdataticket = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        lbdata = new javax.swing.JLabel();
        Painel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(690, 400));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 310, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("RETIRE A SENHA");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 40));
        background.add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 140, 100));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Retirar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Preferencial");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Normal");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Retirar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbsenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel2.add(lbsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 70));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));
        jPanel2.add(lbhoraticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 60, 20));
        jPanel2.add(lbdataticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 80, 20));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 170, 210));

        lbhora.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        background.add(lbhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, 20));

        lbdata.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        background.add(lbdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 120, 20));

        Painel.setBackground(new java.awt.Color(255, 255, 255));
        Painel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Painel.setText("Painel");
        Painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Painel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PainelActionPerformed(evt);
            }
        });
        background.add(Painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 170, 30));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon iconnormal = new ImageIcon("src/img/img_sus.jpg");
        icone.setIcon(iconnormal);
        iconnormal.setImage(iconnormal.getImage().getScaledInstance(icone.getWidth(), icone.getHeight(),1));
        
        Date dataHora = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        lbdata.setText(dt.format(dataHora));
        pegaData = lbdata.getText();
 
        Timer timer = new Timer(1000, new dataHora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        tipo = "N";
        
        pegaSenha(tipo);
        gravabanco();
        
        lbsenha.setText(tipo + "º " + seq);
        lbhoraticket.setText(pegaHora);
        lbdataticket.setText(pegaData);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        tipo = "P";
        
        pegaSenha(tipo);
        gravabanco();
        
        lbsenha.setText(tipo + "º " + seq);
        lbhoraticket.setText(pegaHora);
        lbdataticket.setText(pegaData);
    }//GEN-LAST:event_jButton2MouseClicked

    private void PainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PainelActionPerformed
        telapainel tela = new telapainel();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PainelActionPerformed

    private void gravabanco(){
        String sql = "INSERT INTO tb01_senha VALUES ('" + seq + "', '" + tipo + "', 'N', NOW(), NOW());";   
        
         try{
            objbd.conectar();
            objbd.runSQL(sql);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void pegaSenha(String tipo){
        String sql = "Select max(tb01_num) from tb01_senha ";
               sql += " where id01_tipo = '" + tipo + "'";
            
        try{

        seq = 0;
        int minSenha = 0;
        
                        
        objbd.conectar();

        ResultSet rs = statement.executeQuery(sql);  
       
        if (rs.next()) 
        {
            minSenha = rs.getInt(1);
        }
        
        seq = minSenha + 1; 
        
        objbd.desconectar();
        }
        catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
     
     class dataHora implements ActionListener 
         {
           @Override
           public void actionPerformed(ActionEvent ae) {
                Calendar now = Calendar.getInstance();
                lbhora.setText(String.format("%1$tH:%1$tM:%1$tS", now)); 
                pegaHora = lbhora.getText();
          }
       }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telarec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telarec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telarec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telarec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telarec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Painel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel icone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbdata;
    private javax.swing.JLabel lbdataticket;
    private javax.swing.JLabel lbhora;
    private javax.swing.JLabel lbhoraticket;
    private javax.swing.JLabel lbsenha;
    // End of variables declaration//GEN-END:variables
}
